table CohortRetention

    column cohort_month
        dataType: string
        summarizeBy: none
        sourceColumn: cohort_month

    column cohort_index
        dataType: int64
        formatString: 0
        summarizeBy: none
        sourceColumn: cohort_index

    column cohort_size
        dataType: int64
        formatString: #,##0
        summarizeBy: none
        sourceColumn: cohort_size

    column active_customers
        dataType: int64
        formatString: #,##0
        summarizeBy: none
        sourceColumn: active_customers

    column retention_pct
        dataType: decimal
        formatString: 0.0
        summarizeBy: none
        sourceColumn: retention_pct

    column revenue
        dataType: decimal
        formatString: £#,##0.00
        summarizeBy: none
        sourceColumn: revenue

    partition CohortRetention = m
        mode: import
        source =
                let
                    Source = Csv.Document(File.Contents(DatasetFolder & "/CohortRetention.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cohort_month", type text}, {"cohort_index", Int64.Type}, {"cohort_size", Int64.Type}, {"active_customers", Int64.Type}, {"retention_pct", type number}, {"revenue", type number}})
                in
                    #"Changed Type"

        annotation PBI_ResultType = Table
