table CohortSummary

    column cohort_month
        dataType: string
        summarizeBy: none
        sourceColumn: cohort_month

    column cohort_size
        dataType: int64
        formatString: #,##0
        summarizeBy: none
        sourceColumn: cohort_size

    column repeat_customers
        dataType: int64
        formatString: #,##0
        summarizeBy: none
        sourceColumn: repeat_customers

    column one_time_customers
        dataType: int64
        formatString: #,##0
        summarizeBy: none
        sourceColumn: one_time_customers

    column repeat_rate_pct
        dataType: decimal
        formatString: 0.0
        summarizeBy: none
        sourceColumn: repeat_rate_pct

    column lifetime_revenue
        dataType: decimal
        formatString: £#,##0.00
        summarizeBy: none
        sourceColumn: lifetime_revenue

    column revenue_per_customer
        dataType: decimal
        formatString: £#,##0.00
        summarizeBy: none
        sourceColumn: revenue_per_customer

    column avg_orders_per_customer
        dataType: decimal
        formatString: 0.0
        summarizeBy: none
        sourceColumn: avg_orders_per_customer

    column avg_active_months
        dataType: decimal
        formatString: 0.0
        summarizeBy: none
        sourceColumn: avg_active_months

    column avg_lifetime_days
        dataType: decimal
        formatString: #,##0
        summarizeBy: none
        sourceColumn: avg_lifetime_days

    partition CohortSummary = m
        mode: import
        source =
                let
                    Source = Csv.Document(File.Contents(DatasetFolder & "/CohortSummary.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"cohort_month", type text}, {"cohort_size", Int64.Type}, {"repeat_customers", Int64.Type}, {"one_time_customers", Int64.Type}, {"repeat_rate_pct", type number}, {"lifetime_revenue", type number}, {"revenue_per_customer", type number}, {"avg_orders_per_customer", type number}, {"avg_active_months", type number}, {"avg_lifetime_days", type number}})
                in
                    #"Changed Type"

        annotation PBI_ResultType = Table
