table DimCountry

    column country
        dataType: string
        isKey
        summarizeBy: none
        sourceColumn: country

    column region
        dataType: string
        summarizeBy: none
        sourceColumn: region

    partition DimCountry = m
        mode: import
        source =
                let
                    Source = Csv.Document(File.Contents(DatasetFolder & "/DimCountry.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country", type text}, {"region", type text}})
                in
                    #"Changed Type"

        annotation PBI_ResultType = Table
