table DimCustomer

    column customer_id
        dataType: int64
        isHidden
        isKey
        formatString: 0
        summarizeBy: none
        sourceColumn: customer_id

    column first_order_date
        dataType: dateTime
        formatString: dd mmm yyyy
        summarizeBy: none
        sourceColumn: first_order_date

    column last_order_date
        dataType: dateTime
        formatString: dd mmm yyyy
        summarizeBy: none
        sourceColumn: last_order_date

    column recency_days
        dataType: int64
        formatString: #,##0
        summarizeBy: average
        sourceColumn: recency_days

    column frequency
        dataType: int64
        formatString: #,##0
        summarizeBy: average
        sourceColumn: frequency

    column monetary
        dataType: decimal
        formatString: £#,##0.00
        summarizeBy: sum
        sourceColumn: monetary

    column r_score
        dataType: int64
        formatString: 0
        summarizeBy: average
        sourceColumn: r_score

    column f_score
        dataType: int64
        formatString: 0
        summarizeBy: average
        sourceColumn: f_score

    column m_score
        dataType: int64
        formatString: 0
        summarizeBy: average
        sourceColumn: m_score

    column rfm_score
        dataType: int64
        formatString: 0
        summarizeBy: average
        sourceColumn: rfm_score

    column customer_lifetime_days
        dataType: int64
        formatString: #,##0
        summarizeBy: average
        sourceColumn: customer_lifetime_days

    column is_repeat
        dataType: int64
        formatString: 0
        summarizeBy: sum
        sourceColumn: is_repeat

    column first_purchase_year_month
        dataType: string
        summarizeBy: none
        sourceColumn: first_purchase_year_month

    column segment
        dataType: string
        summarizeBy: none
        sourceColumn: segment

    partition DimCustomer = m
        mode: import
        source =
                let
                    Source = Csv.Document(File.Contents(DatasetFolder & "/DimCustomer.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"first_order_date", type date}, {"last_order_date", type date}, {"recency_days", Int64.Type}, {"frequency", Int64.Type}, {"monetary", type number}, {"r_score", Int64.Type}, {"f_score", Int64.Type}, {"m_score", Int64.Type}, {"rfm_score", Int64.Type}, {"customer_lifetime_days", Int64.Type}, {"is_repeat", Int64.Type}, {"first_purchase_year_month", type text}, {"segment", type text}})
                in
                    #"Changed Type"

        annotation PBI_ResultType = Table
