table DimProduct

    column stock_code
        dataType: string
        isKey
        summarizeBy: none
        sourceColumn: stock_code

    column description
        dataType: string
        summarizeBy: none
        sourceColumn: description

    column category
        dataType: string
        summarizeBy: none
        sourceColumn: category

    partition DimProduct = m
        mode: import
        source =
                let
                    Source = Csv.Document(File.Contents(DatasetFolder & "/DimProduct.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"stock_code", type text}, {"description", type text}, {"category", type text}})
                in
                    #"Changed Type"

        annotation PBI_ResultType = Table
